- name: Install Kitty
  become: yes
  pacman:
          name: kitty
          state: present

- name: Install Hack Nerd font
  become: yes
  pacman:
    name: ttf-hack-nerd
    state: present

- name: Symlink Kitty configuration
  file:
          src: "{{ ansible_env.PWD }}/roles/kitty/files/kitty"
          path: ~/.config/kitty
          state: link
          force: yes
