- name: Install Kitty
  become: yes
  pacman:
          name: kitty
          state: present

- name: Install Nerd fonts
  aur:
      name: nerd-fonts-complete
      skip_installed: yes
      use: yay

- name: Symlink Kitty configuration
  file:
          src: "{{ ansible_env.PWD }}/roles/kitty/files/kitty"
          path: ~/.config/kitty
          state: link
          force: yes
