- name: Install Zsh
  become: yes
  pacman:
          name: zsh
          state: present
- name: Install Zsh Completions
  become: yes
  pacman:
          name: zsh-completions
          state: present

- name: Install Zsh Syntax highlighting
  become: yes
  pacman:
          name: zsh-syntax-highlighting
          state: present

- name: Install Zsh Autosuggestions
  become: yes
  pacman:
          name: zsh-autosuggestions
          state: present

- name: Set shell for user pablo
  become: yes
  user:
          name: pablo
          shell: /bin/zsh

- name: Install Oh my zsh
  aur:
          name: oh-my-zsh-git

- name: Create local plugins directory
  file:
          path: ~/.oh-my-zsh/custom/plugins
          state: directory

- name: Install Vi mode agnoster plugin.
  copy:
          dest: ~/.oh-my-zsh/custom/plugins/vi-mode-agnoster.plugin.zsh
          src: "{{ ansible_env.PWD }}/roles/zsh/files/vi-mode-agnoster.plugin.zsh"

- name: Symlink Zsh configuration
  file:
          src: "{{ ansible_env.PWD }}/roles/zsh/files/.zshrc"
          path: ~/.zshrc
          state: link
          force: yes
