- name: Install Xmonad
  become: yes
  pacman:
          name: xmonad
          state: present
          name: xmonad-contrib
          state: present

- name: Create Xmonad configuration folder
  file:
      path: ~/.xmonad
      state: directory

- name: Symlink Xmonad config
  file: src={{ ansible_env.PWD }}/roles/xmonad/files/xmonad.hs
        path=~/.xmonad/xmonad.hs
        state=link
        force=yes

- name: Install Xmobar
  become: yes
  pacman:
          name: xmobar
          state: present

- name: Symlink Xmobar configuration
  file: 
    src: "{{ ansible_env.PWD }}/roles/xmonad/files/.xmobarrc"
    path: ~/.xmobarrc
    state: link
    force: yes
- name: Create Xmobar directory
  file:
          path: ~/.config/xmobar
          state: directory

- name: Link to Xmobar images
  file:
          src: "{{ ansible_env.PWD }}/roles/xmonad/files/xpm"
          path: ~/.config/xmobar/xpm
          state: link
          force: yes

- name: Set Xmonad as default desktop
  become: yes
  copy:
      src: /usr/share/xsessions/xmonad.desktop
      dest: /usr/share/xsessions/default.desktop

- name: Ensure the hooks folder for Pacman exists
  become: yes
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Hook to recompile Xmonad upon update
  become: yes
  template:
    src: "{{ ansible_env.PWD }}/roles/xmonad/templates/pacman-hook.j2"
    dest: "/etc/pacman.d/hooks/xmonad-{{ ansible_user_id }}.hook"

- name: Install Haskell Language Server
  become: yes
  pacman:
    name: haskell-language-server
    state: present
