- name: Install GTK 2
  become: yes
  pacman:
    name: gtk2
    state: present

- name: Install GTK 3
  become: yes
  pacman:
    name: gtk3
    state: present

- name: Install GTK 4
  become: yes
  pacman:
    name: gtk4
    state: present

- name: Install LxAppearance
  become: yes
  pacman:
    name: lxappearance
    state: present

- name: Install Dracula Theme
  aur:
    name: dracula-gtk-theme
    state: present

- name: Install Dracula cursors
  aur:
    name: dracula-cursors-git
    state: present

- name: Install Dracula icons
  aur:
    name: dracula-icons-git
    state: present

- name: Copy configuration for GTK 2
  copy:
    src: "{{ ansible_env.PWD }}/roles/gtk/files/.gtkrc-2.0"
    dest: "~/.gtkrc-2.0"

- name: Create GTK 3 configuration folder
  file:
    path: "~/.config/gtk-3.0"
    state: directory

- name: Copy GTK 3 configuration
  copy:
    src: "{{ ansible_env.PWD }}/roles/gtk/files/gtk-3.0/settings.ini"
    dest: "~/.config/gtk-3.0/settings.ini"

- name: Copy mouse cursor configuration
  copy:
    src: "{{ ansible_env.PWD }}/roles/gtk/files/.icons"
    dest: "~/"
    directory_mode:


