- name: Install Java runtime commons package
  become: yes
  pacman:
      name: java-runtime-common
      state: present

- name: Install Java environment commons package
  become: yes
  pacman:
      name: java-environment-common
      state: present

- name: Install OpenJDK 8
  become: yes
  pacman:
      name: jdk8-openjdk
      state: present

- name: Install Gradle
  become: yes
  pacman:
    name: gradle
    state: present

- name: Install Maven
  become: yes
  pacman:
    name: maven
    state: present

- name: Install JDTLS LSP
  aur:
    name: jdtls
    use: yay
