- name: Full system upgrade
  import_tasks: archupgrade.yml
  when: ansible_facts['os_family']|lower == 'arch'

- name: Install alsa utils
  become: yes
  pacman:
          name: alsa-utils
          state: present

- name: Install X-Windows
  become: yes
  pacman:
          name: xorg
          state: present

- name: Install accounts service
  become: yes
  pacman:
          name: accountsservice
          state: present

- name: Install dmenu
  become: yes
  pacman:
          name: dmenu
          state: present

- name: Set xprofile file
  file:
      src: "{{ ansible_env.PWD }}/roles/common/files/.xprofile"
      path: ~/.xprofile
      state: link
      force: yes

- name: Install qutebrowser
  become: yes
  pacman:
          name: qutebrowser
          state: present

- name: Create qutebrowser configuration directory
  file:
      path: ~/.config/qutebrowser
      state: directory

- name: Symlink qutebrowser configuration
  file: src={{ ansible_env.PWD }}/roles/common/files/.qutebrowser/config.py
        path=~/.config/qutebrowser/config.py
        state=link
        force=yes

- name: Install neofetch
  become: yes
  pacman:
          name: neofetch
          state: present

- name: Install clipmenu
  become: yes
  pacman:
          name: clipmenu
          state: present

- name: Install Clipnotify
  become: yes
  pacman:
          name: clipnotify
          state: present
- name: Install libnotify
  become: yes
  pacman:
          name: libnotify
          state: present

- name: Install fzf
  become: yes
  pacman:
      name: fzf
      state: present

- name: install tldr++
  aur:
          name: tldr++
          use: yay

- name: Install text-based web browser
  become: yes
  pacman:
      name: w3m
      state: present
