- name: Full system upgrade
  import_tasks: archupgrade.yml
  when: ansible_facts['os_family']|lower == 'arch'

- name: Install Pacman contrib
  become: true
  pacman:
    name: pacman-contrib
    state: present

- name: Ensure the hooks folder for Pacman exists
  become: true
  file:
    path: /etc/pacman.d/hooks
    state: directory

- name: Copy clean cache hook
  become: true
  copy:
    src: "{{ ansible_env.PWD }}/roles/common/files/hooks/clean-cache.hook" 
    dest: /etc/pacman.d/hooks/clean-cache.hook

- name: Install alsa utils
  become: true
  pacman:
          name: alsa-utils
          state: present

- name: Install X-Windows
  become: true
  pacman:
          name: xorg
          state: present

- name: Install accounts service
  become: true
  pacman:
          name: accountsservice
          state: present

- name: Install dmenu
  become: true
  pacman:
          name: dmenu
          state: present

- name: Set xprofile file
  file:
      src: "{{ ansible_env.PWD }}/roles/common/files/.xprofile"
      path: ~/.xprofile
      state: link
      force: yes

- name: Install qutebrowser
  become: true
  pacman:
          name: qutebrowser
          state: present

- name: Create qutebrowser configuration directory
  file:
      path: ~/.config/qutebrowser
      state: directory

- name: Add theme
  file:
    src: "{{ ansible_env.PWD }}/roles/common/files/dracula-qutebrowser"
    path: "~/.config/qutebrowser/dracula"
    state: link
    force: yes

- name: Symlink qutebrowser configuration
  file: src={{ ansible_env.PWD }}/roles/common/files/.qutebrowser/config.py
        path=~/.config/qutebrowser/config.py
        state=link
        force=yes

- name: Install fastfetch
  become: true
  pacman:
          name: fastfetch
          state: present

- name: Install clipmenu
  become: true
  pacman:
          name: clipmenu
          state: present

- name: Install xclip
  become: true 
  pacman:
    name: xclip
    state: present

- name: Install Clipnotify
  become: true
  pacman:
          name: clipnotify
          state: present

- name: Install libnotify
  become: true
  pacman:
          name: libnotify
          state: present

- name: Install fzf
  become: true
  pacman:
      name: fzf
      state: present

- name: install tldr++
  aur:
          name: tldr++
          use: yay

- name: Install text-based web browser
  become: true
  pacman:
      name: w3m
      state: present

- name: Install udisks2
  become: true
  pacman:
      name: udisks2
      state: present

- name: Install udiskie
  become: true
  pacman:
      name: udiskie
      state: present

- name: Set profile file
  file:
      src: "{{ ansible_env.PWD }}/roles/common/files/.profile"
      path: ~/.profile
      state: link
      force: yes

- name: Install Dragon drag and drop
  aur:
    name: dragon-drop
    use: yay
