- name: Install Alacritty
  become: yes
  pacman:
      name: alacritty
      state: present

- name: Symlink Alacritty configuration folder
  file:
      src: "{{ ansible_env.PWD }}/roles/alacritty/files/alacritty"
      path: "~/.config/alacritty"
      state: link
      force: yes

- name: Install Hack Nerd font
  become: yes
  pacman:
    name: ttf-hack-nerd
    state: present
