- name: Install dunst
  become: yes
  pacman:
          name: dunst
          state: present

- name: Create dunst configuration directory
  file:
          path: ~/.config/dunst
          state: directory

- name: Set dunst configuration
  file:
          src: "{{ ansible_env.PWD }}/roles/dunst/files/dunstrc"
          path: ~/.config/dunst/dunstrc
          state: link
          force: yes

