- name: Install lf
  aur:
    name: lf-bin

- name: Install exiftools
  become: yes
  pacman:
    name: perl-image-exiftool
    state: present

- name: Make sure the configuration directory exists
  file:
    path: ~/.config/lf
    state: directory

- name: Symlink configuration
  file:
    src: "{{ ansible_env.PWD }}/roles/lf/files/lfrc"
    path: ~/.config/lf/lfrc
    state: link
