- name: Install mpv
  become: yes
  pacman:
      name: mpv
      state: present

- name: Link configuration
  file:
    src: "{{ ansible_env.PWD }}/roles/mpv/files/mpv.conf"
    path: ~/.config/mpv/mpv.conf
    state: link
