- name: Install Neovim
  become: yes
  pacman:
          name: neovim
          state: present

- name: Install Python support for Neovim
  become: yes
  pacman:
          name: python-pynvim
          state: present

- name: Symlink configuration
  file:
          src: "{{ ansible_env.PWD }}/roles/vim/files/nvim"
          path: ~/.config/nvim
          state: link
          force: yes

- name: Install plugins
  get_url:
      url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Configure Neovim
  shell: nvim +PlugInstall +UpdateRemotePlugins +qa
