#!/bin/sh
status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
[ "$capacity" -le 10 ] && [ "$status" = "Discharging" ] && \
    notify-send -u critical 'Battery running out' 'Please, connect the charger before the computer hibernates'

