#!/bin/sh
export GRADLE_HOME=$HOME/gradle 
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk 
jdtls \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
    -Dlog.level=ALL \
    -Xmx2G \
    --add-modules=ALL-SYSTEM \
    --add-opens java.base/java.util=ALL-UNNAMED \
    --add-opens java.base/java.lang=ALL-UNNAMED
