#!/bin/sh
server=$HOME/repos/lsp/java/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository/
jar="$server/plugins/org.eclipse.equinox.launcher_*.jar" 
/usr/lib/jvm/java-15-openjdk/bin/java \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.level=ALL \
    -noverify \
    -Xmx1G \
    -jar $(echo $jar) \
    -configuration $server/config_linux/ \
    -data "$HOME/repos/projects/"
