- name: Install Docker
  become: yes
  pacman:
    name: docker 
    state: present

- name: Enable Docker service
  become: yes
  systemd:
    name: docker 
    enabled: yes
    state: started

- name: Add current user to docker group
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes

- name: Install Docker compose
  become: yes
  pacman:
    name: docker-compose 
    state: present
