source ~/.config/nvim/general_config.vim
source ~/.config/nvim/plugins.vim
source ~/.config/nvim/visuals_config.vim
source ~/.config/nvim/keybindings.vim
source ~/.config/nvim/ack_config.vim
source ~/.config/nvim/nerdtree_config.vim
source ~/.config/nvim/crontab_config.vim
source ~/.config/nvim/lsp_config.vim
source ~/.config/nvim/whichkey_config.vim
source ~/.config/nvim/rainbow_config.vim
luafile ~/.config/nvim/treesitter.lua
source ~/.config/nvim/completion.vim
