- name: Install Android Studio
  aur:
      name: android-studio
      skip_installed: yes
      use: yay

- name: Link IdeaVim configuration
  file:
      src: "{{ ansible_env.PWD }}/roles/android/files/.ideavimrc"
      path: ~/.ideavimrc
      state: link
      force: yes
