- name: Install TaskWarrior
  become: yes
  pacman:
      name: task
      state: present

- name: Set Taskwarrior configuration
  file:
      src: "{{ ansible_env.PWD }}/roles/taskwarrior/files/.taskrc"
      path: ~/.taskrc
      state: link
      force: yes

- name: Install Vit
  become: yes 
  pacman:
    name: vit
    state: present

- name: Install TaskOpen
  aur:
    name: taskopen

- name: Set up configuration for TaskOpen
  file:
      src: "{{ ansible_env.PWD }}/roles/taskwarrior/files/taskopen"
      path: ~/.config/taskopen
      state: link
      force: yes

